import{S as v,i as S}from"./assets/vendor-e663445a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const f="44852213-a2483cc0047435af0fdb3dda4",h="https://pixabay.com/api/";async function p(r,t=1,o=15){try{const s=await fetch(`${h}?key=${f}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${o}`);if(console.log("Fetch URL:",`${h}?key=${f}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${o}`),!s.ok)throw new Error("Failed to fetch images");const e=await s.json();return console.log("Fetched data:",e),e}catch(s){throw console.error("Error fetching images:",s),s}}const y=document.querySelector(".gallery"),g=document.querySelector(".load-more"),q=new v(".gallery a");function _(){y.innerHTML=""}function L(r){const t=r.map(o=>`
        <a href="${o.largeImageURL}" class="gallery__item">
            <img src="${o.webformatURL}" alt="${o.tags}" title="${o.tags}" class="gallery__image"/>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${o.likes}</p>
                <p class="info-item"><b>Views:</b> ${o.views}</p>
                <p class="info-item"><b>Comments:</b> ${o.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${o.downloads}</p>
            </div>
        </a>
    `).join("");y.insertAdjacentHTML("beforeend",t),q.refresh()}function a(r){S.info({message:r,position:"topRight"})}function w(){document.querySelector(".loader").classList.remove("hidden")}function $(){document.querySelector(".loader").classList.add("hidden")}function b(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}let i=1,c="",u=0;const P=document.querySelector("#search-form"),m=document.querySelector("#search-input"),E=document.querySelector(".load-more");P.addEventListener("submit",async r=>{if(r.preventDefault(),c=m.value.trim(),!c){a("Please enter a search term!");return}i=1,u=0,w(),d(),_();try{const t=await p(c,i);u=t.totalHits,t.length===0?a("Sorry, there are no images matching your search query. Please try again!"):(L(t.hits),t.hits.length>=15&&b()),m.value=""}catch{a("An error occurred while fetching images. Please try again later.")}finally{$()}});E.addEventListener("click",async()=>{i+=1,w(),d();try{const r=await p(c,i);(i-1)*15+r.hits.length>=u?(d(),a("No more images found!")):(L(r.hits),b())}catch{a("An error occurred while fetching images. Please try again later.")}finally{$()}});
//# sourceMappingURL=commonHelpers.js.map
