import{S as b,i as $}from"./assets/vendor-e663445a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const v="44852213-a2483cc0047435af0fdb3dda4",S="https://pixabay.com/api/";async function f(s,r=1,t=15){try{const n=await fetch(`${S}?key=${v}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${t}`);if(!n.ok)throw new Error("Failed to fetch images");return await n.json()}catch(n){throw console.error("Error fetching images:",n),n}}const m=document.querySelector(".gallery"),h=document.querySelector(".load-more"),q=new b(".gallery a");function P(){m.innerHTML=""}function y(s){const r=s.map(t=>`
        <a href="${t.largeImageURL}" class="gallery__item">
            <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}" class="gallery__image"/>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t.likes}</p>
                <p class="info-item"><b>Views:</b> ${t.views}</p>
                <p class="info-item"><b>Comments:</b> ${t.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </a>
    `).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function a(s){$.info({message:s,position:"topRight"})}function p(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function L(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}let i=1,c="",w=0;const _=document.querySelector("#search-form"),u=document.querySelector("#search-input"),E=document.querySelector(".load-more");_.addEventListener("submit",async s=>{if(s.preventDefault(),c=u.value.trim(),!c){a("Please enter a search term!");return}i=1,w=0,p(),d(),P();try{const r=await f(c,i);r.length===0?a("Sorry, there are no images matching your search query. Please try again!"):(y(r),L()),u.value=""}catch{a("An error occurred while fetching images. Please try again later.")}finally{g()}});E.addEventListener("click",async()=>{i+=1,p(),d();try{const s=await f(c,i);(i-1)*15+data.hits.length>=w?(d(),a("No more images found!")):(y(data.hits),L())}catch{a("An error occurred while fetching images. Please try again later.")}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
