import{S as w,i as S}from"./assets/vendor-e663445a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&e(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const $="44852213-a2483cc0047435af0fdb3dda4",v="https://pixabay.com/api/";async function f(a,r=1,s=16){try{const e=await fetch(`${v}?key=${$}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`);if(!e.ok)throw new Error("Failed to fetch images");return(await e.json()).hits}catch(e){throw console.error("Error fetching images:",e),e}}const m=document.querySelector(".gallery"),p=document.querySelector(".load-more");function P(){m.innerHTML=""}function h(a){const r=a.map(e=>`
        <a href="${e.largeImageURL}" class="gallery__item">
            <img src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}" class="gallery__image"/>
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${e.likes}</p>
                <p class="info-item"><b>Views:</b> ${e.views}</p>
                <p class="info-item"><b>Comments:</b> ${e.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
            </div>
        </a>
    `).join("");m.insertAdjacentHTML("beforeend",r),new w(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"title",captionPosition:"bottom",captionDelay:250,animationSpeed:300,fadeSpeed:400,docClose:!0,swipeClose:!0,loop:!0,preloading:!0}).refresh()}function n(a){S.info({message:a,position:"topRight"})}function y(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function L(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}let i=1,c="",b=0;const q=document.querySelector("#search-form"),u=document.querySelector("#search-input"),_=document.querySelector(".load-more");q.addEventListener("submit",async a=>{if(a.preventDefault(),c=u.value.trim(),!c){n("Please enter a search term!");return}i=1,b=0,y(),d(),P();try{const r=await f(c,i);r.length===0?n("Sorry, there are no images matching your search query. Please try again!"):(h(r),L()),u.value=""}catch{n("An error occurred while fetching images. Please try again later.")}finally{g()}});_.addEventListener("click",async()=>{i+=1,y(),d();try{const a=await f(c,i);(i-1)*15+data.hits.length>=b?(d(),n("No more images found!")):(h(data.hits),L())}catch{n("An error occurred while fetching images. Please try again later.")}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
